name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release (Steam Workshop)
    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: |
          wget "https://github.com/hmlendea/imperator-rtw-style-loading-screens/releases/download/${{github.ref_name}}/rtw-style-loading-screens_${GITHUB_REF:11}.zip" -O "rtw-style-loading-screens.zip"
          unzip "rtw-style-loading-screens.zip" -d "rtw-style-loading-screens/"

    - name: Upload
      uses: hmlendea/steam-workshop-update@latest
      with:
        appid: '859580'
        itemid: '3513150774'
        path: "rtw-style-loading-screens/"
        changenote: "[url=https://github.com/hmlendea/imperator-rtw-style-loading-screens/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_2FASEED: ${{secrets.STEAM_2FASEED}}
